### ISSUE TITLE
Rollergate

### ISSUE THREAD

**Issue by tnilss13** [Piotr-Grochowski/eu.blebox#6]
Hello
I have à problem with my two rollergates. They stop working in Homey. Homey cant detect them.
I then need to restart the app. This happens 2-3 times a day.

**Comment by Piotr-Grochowski** [comment]
Please generate a diagnostic report and let me know to check it.

**Comment by tnilss13** [comment]
3ddea68c-2eaa-4479-955e-330140f37f0f

Skickat från min iPad

8 maj 2023 kl. 19:58 skrev Piotr-Grochowski ***@***.***>:

﻿

Please generate a diagnostic report and let me know to check it.

**Comment by Piotr-Grochowski** [comment]
Maybe I made too much shortcut. I meant to send me the diagnostic report next time you have a problem with the device. From this report I can see no errors...

**Comment by Piotr-Grochowski** [comment]
OK, I can see that you've got one gateBox and one rollerGate and both of them have the same problem - Homey loses communication with both of them at the same time:

[log] 2023-05-08 18:22:07 [ManagerDrivers] [Driver:rollergate] [Device:34bd1c6f-6d35-472e-a7a2-9e7d0fdf423f] Error: connect EHOSTUNREACH 192.168.50.221:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.50.221',
  port: 80
}
[log] 2023-05-08 18:22:11 [ManagerDrivers] [Driver:gatebox] [Device:80cba673-883a-4f35-b7fa-0bcbf0210479] Error: connect EHOSTUNREACH 192.168.50.73:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.50.73',
  port: 80
}

EHOSTUNREACH means that host is not reachable. So, it seems that there might be a problem with the WiFi communication - between Homey and router and/or BleBoxes and router. Also the communication might be slow and due to polling interval Homey may run out of connections available.

So:
1. Please check your connections quality
2. Try to make a longer polling interval (e.g. 5000ms instead of standard 1000ms)

and please let me know if it's better.

Also - do you restart only BleBox app or the whole Homey after devices become unavailable?

**Comment by tnilss13** [comment]
Thank you for the help, it’s working now.

Skickat från min iPhone

8 maj 2023 kl. 20:40 skrev Piotr-Grochowski ***@***.***>:

﻿

OK, I can see that you've got one gateBox and one rollerGate and both of them have the same problem - Homey loses communication with both of them at the same time:

[log] 2023-05-08 18:22:07 [ManagerDrivers] [Driver:rollergate] [Device:34bd1c6f-6d35-472e-a7a2-9e7d0fdf423f] Error: connect EHOSTUNREACH 192.168.50.221:80
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
errno: -113,
code: 'EHOSTUNREACH',
syscall: 'connect',
address: '192.168.50.221',
port: 80
}
[log] 2023-05-08 18:22:11 [ManagerDrivers] [Driver:gatebox] [Device:80cba673-883a-4f35-b7fa-0bcbf0210479] Error: connect EHOSTUNREACH 192.168.50.73:80
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
errno: -113,
code: 'EHOSTUNREACH',
syscall: 'connect',
address: '192.168.50.73',
port: 80
}

EHOSTUNREACH means that host is not reachable. So, it seems that there might be a problem with the WiFi communication - between Homey and router and/or BleBoxes and router. Also the communication might be slow and due to polling interval Homey may run out of connections available.

So:

  1.  Please check your connections quality
  2.  Try to make a longer polling interval (e.g. 5000ms instead of standard 1000ms)

and please let me know if it's better.

Also - do you restart only BleBox app or the whole Homey after devices become unavailable?
